### ISSUE TITLE
Update deFusion Staked VIC (SVIC) info 15.3.2024

### ISSUE THREAD

**Issue by defusionintern** [BuildOnViction/tokens#413]
**Token Address**
https://www.vicscan.xyz/token/0xCdde1f5D971A369eB952192F9a5C367f33a0A891

**Token Symbol**
SVIC

**Token Name**
deFusion Staked VIC

**Token Logo**
![SVIC-Logo_Icon](https://github.com/BuildOnViction/tokens/assets/163391870/ee9918cd-3ce3-40d5-80ed-6a0b30ca196f)

Token Description
The SVIC token is a tokenized version of staked VIC. When a user sends VIC into the deFusion liquid staking smart contract, the user receives the corresponding amount of SVIC tokens.

Website
https://www.defusion.xyz/

Social links
[Twitter](https://twitter.com/deFusionxyz)
[Telegram](https://t.me/deFusion_ann)
[Discord](https://discord.gg/ZWJnP4UygJ)

**Comment by bobcoin98** [comment]
closed in 92719b23ba00fb597777a3d2b176e5feb0a9c165
