### ISSUE TITLE
Update token information for VIN token

### ISSUE THREAD

**Issue by VinLottery** [BuildOnViction/tokens#435]
**Token Address**
https://vicscan.xyz/address/0x941f63807401efce8afe3c9d88d368baa287fac4

**Token Symbol**
VIN

**Token Name**
VinLottery

**Token Logo**
![941f63807401efce8afe3c9d88d368baa287fac4](https://github.com/user-attachments/assets/b8038f75-7b10-4de4-a152-da05a709047e)

**Token Description**
Value, opportunity, and global lotteries.

**Website**
https://lottery.vin

**Social links**
Github: https://github.com/VinLottery
Telegram Group: https://t.me/VinLotteryGroup
Telegram Channel: https://t.me/VinLottery
Twitter: https://twitter.com/VinLottery

**Comment by VinLottery** [comment]
Hi team,  
I have completed the payment of 10 VIC for the VIN token logo update.  

- Transaction Hash: [0x4890c41a3daf8ebcd1f5272ca324eaed0102609e9a22ca1417fe3f4e6d09b6c6]:  https://www.vicscan.xyz/tx/0x4890c41a3daf8ebcd1f5272ca324eaed0102609e9a22ca1417fe3f4e6d09b6c6  

Please proceed with the update. Thank you!

**Comment by tungng98** [comment]
Completed in commit 34ed310013259d00544ccd712b020708b68ac5b1
